"""empty message

Revision ID: 6ebac5f76305
Revises: 530742ad98bd
Create Date: 2017-12-03 21:40:03.056431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ebac5f76305'
down_revision = '530742ad98bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('voted_round1', sa.Text(), nullable=True))
    op.add_column('players', sa.Column('voted_round2', sa.Text(), nullable=True))
    op.add_column('players', sa.Column('voted_round3', sa.Text(), nullable=True))
    op.add_column('players', sa.Column('voted_round4', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'voted_round4')
    op.drop_column('players', 'voted_round3')
    op.drop_column('players', 'voted_round2')
    op.drop_column('players', 'voted_round1')
    # ### end Alembic commands ###
